### ISSUE TITLE
homepage says "Xi Zulip"

### ISSUE THREAD

**Issue by simbleau** [linebender/linebender.github.io#46]
The homepage of linebender.org points to the "Xi Zulip" instance

**Comment by Philipp-M** [comment]
Have I missed something? Is there a new instance? AFAIK, it was decided some while back, that renaming the instance would be too much of a hassle.

**Comment by simbleau** [comment]
Yea, apologies for the confusion. To be clear, the text should be renamed to "Linebender Zulip" but the link should remain.
